### PR TITLE
Add header, proper name to project

### PR DESCRIPTION
**Pull request by chris-sarli**
This PR adds a header to the interface, and names this entire product/project "[TBD]".

### CODE REVIEW

**Comment by chris-sarli** [comment]
@tukensam here's the work so far on the header. Waiting to merge until a name is decided upon.

**Comment by chris-sarli** [comment]
@tukensam So was Jane ok with "Das Bücherregal" as the name?

**Comment by chris-sarli** [comment]
Still to do:
- Change urls
- change repo and conda names
- Favicon?

**Comment by tukensam** [comment]
ue is often used to replace ü

**Comment by chris-sarli** [comment]
Ok. Will discuss in meeting tomorrow.

**Pull request merged**
